export const USE_CASES_FRAMEWORK_TYPES = {
    USE_CASES_LOADER: Symbol("USE_CASES_LOADER"),
    USE_CASES_FRAMEWORK: Symbol("USE_CASES_FRAMEWORK"),
    USE_CASES_CONTAINER: Symbol("USE_CASES_CONTAINER"),
    USE_CASES_FACTORY: Symbol("USE_CASES_FACTORY")
}